export const USERS_CATEGORIES = {
  DOCTOR: 'DOCTOR',
  OTHER: 'OTHER',
  PHARMACIST_OR_PHARMACIST: 'PHARMACIST OR PHARMACIST',
  REPRESENTATIVE_OF_A_PHARMACEUTICAL_COMPANY:
    'REPRESENTATIVE OF A PHARMACEUTICAL COMPANY',
  SECONDARY_MEDICAL_PERSONNEL: 'SECONDARY MEDICAL PERSONNEL',
  STUDENT_OR_RESIDENT: 'STUDENT OR RESIDENT',
};
